### PR TITLE
New db connection

### PR DESCRIPTION
**Pull request by myarjunar**
issue #12 #13 

database connection_066

create a new postgis connection_067

### CODE REVIEW

**Comment by NyakudyaA** [comment]
@myarjunar  Can you make sure that when a user is defining a new connection it then automatically becomes the default connection, just like the way add new PostGIS connection does. Also, add a hover tooltip on each icon so that users know what the icons are used for.


out_1

Also on the add new PostGIS connection, I see it is different from the one in Add Postgis. There is no test connection.

In the QGIS
new

In parcel plugin
con

It would be nice to have that test connection so that you can see if your db credentials are fine. A user will then not proceed before completing this.


[postgres service file](https://www.postgresql.org/docs/9.0/static/libpq-pgservice.html) is not working with the plugin if you add a new connection with a service definition

**Comment by myarjunar** [comment]
> It would be nice to have that test connection so that you can see if your db credentials are fine. A user will then not proceed before completing this.

@NyakudyaA I planned to do so, to use native postgres connection manager. But turned out that we can't use any functionalities from qgis provider, manage new pg connection and test connection are from qgis provider. So, for now, the only possible thing is to reimplement it in python. And perhaps we can create our own way to test the connection, not using the native one.

**Comment by NyakudyaA** [comment]
It seems passwords are still not being remembered. 
db

Removing the established connection from Postgres provider seems not to be in sync with the plugin connection. This causes QGIS to crash
fix

Service file seems not be working as well.

**Comment by myarjunar** [comment]
connection using service file:
connect-using-service-file

remember credentials:
save-credentials

also @NyakudyaA , I think we should simplify the new db connection dialog, we should show only the cumpulsory parameters, user can define the other parameters later using the original dialog one. what do you think?

**Comment by myarjunar** [comment]
Define DB dialog:
define-db

**Comment by NyakudyaA** [comment]
When using the service file it still asks for a username and password. Can you make sure that it does not do this and after that you can merge the PR because everything else works

**Pull request merged**
